<?php

namespace Bl\FatooraZatca\Exemptions;

class ZeroRate
{
    const EXPORT_OF_GOODS = 'VATEX-SA-32';
    const EXPORT_OF_SERVICES = 'VATEX-SA-33';
    const TRANSPORT_GOODS = 'VATEX-SA-34-1';
    const TRANSPORT_PASSENGERS = 'VATEX-SA-34-2';
    const TRANSPORT_PASSENGERS_SERVICES = 'VATEX-SA-34-3';
    const TRANSPORT_QUALIFYING = 'VATEX-SA-34-4';
    const TRANSPORT_GOODS_OR_PASSENGERS = 'VATEX-SA-34-5';
    const MEDICINES_AND_MEDICAL_EQUIPMENT = 'VATEX-SA-35';
    const QUALIFYING_METALS = 'VATEX-SA-36';
    const PRIVATE_EDUCATION_TO_CITIZEN = 'VATEX-SA-EDU';
    const PRIVATE_EDUCATION_TO_HEALTHCARE = 'VATEX-SA-HEA';
    const MILITARY_GOODS = 'VATEX-SA-MLTRY';
}
